image: node:15.6.0
pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - node
        script:
          - yarn install
          - yarn test
  branches:
    develop:
      - step:
          name: Build and Test
          caches:
            - node
          artifacts:
            - coverage/lcov.info
          script:
            - yarn install
            - yarn test --coverage
      - step:
          name: Sonar
          image: openjdk:8
          script:
            - curl --insecure -OL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
            - unzip sonar-scanner-cli-4.6.2.2472-linux.zip
            - ./sonar-scanner-4.6.2.2472-linux/bin/sonar-scanner -Dsonar.host.url=https://sonar.jsninjas.net