export const enum CONTRACT_TYPES {
  PURCHASE = "PURCHASE",
}

export const enum CONTRACT_SCREEN_TYPES {
  USER_DATA = "USER_DATA",
  PRODUCT_DATA = "PRODUCT_DATA",
  PRODUCT_CONDITION = "PRODUCT_CONDITION",
  CONFIRMATION = "CONFIRMATION",
  PRODUCT_DESCRIPTION = "PRODUCT_DESCRIPTION",
}

export const CONTRACT_CREATION_WAIT = "CONTRACT_CREATION_WAIT";
