export const enum CONTRACT_TYPES {
    PURCHASE = 'PURCHASE'
}

export const enum CONTRACT_SCREEN_TYPES {
    USER_DATA = 'USER_DATA',
    PRODUCT_DATA = 'PRODUCT_DATA'
}

export const CONTRACT_CREATION_WAIT = 'CONTRACT_CREATION_WAIT'